const StudentArray = [
    {
        id:1,
        name:"Diya",
        fname:"XX",
        mname:"XX",
        mobile:9135467642,
        email:"diya@gmail.com",
        course:"BCA",
        session:"2023-27",
        status:1
    },
    {
        id:2,
        name:"Diya",
        fname:"XX",
        mname:"XX",
        mobile:9135467642,
        email:"diya@gmail.com",
        course:"BCA",
        session:"2023-27",
        status:0
    },
    {
        id:3,
        name:"Diya",
        fname:"XX",
        mname:"XX",
        mobile:9135467642,
        email:"diya@gmail.com",
        course:"BCA",
        session:"2023-27",
        status:0
    },
    {
        id:4,
        name:"Diya",
        fname:"XX",
        mname:"XX",
        mobile:9135467642,
        email:"diya@gmail.com",
        course:"BCA",
        session:"2023-27",
        status:0
    },
    {
        id:5,
        name:"Diya",
        fname:"XX",
        mname:"XX",
        mobile:9135467642,
        email:"diya@gmail.com",
        course:"BCA",
        session:"2023-27",
        status:1
    },
    {
        id:6,
        name:"Diya",
        fname:"XX",
        mname:"XX",
        mobile:9135467642,
        email:"diya@gmail.com",
        course:"BCA",
        session:"2023-27",
        status:0
    },
    {
        id:7,
        name:"Diya",
        fname:"XX",
        mname:"XX",
        mobile:9135467642,
        email:"diya@gmail.com",
        course:"BCA",
        session:"2023-27",
        status:0
    },
    {
        id:8,
        name:"Diya",
        fname:"XX",
        mname:"XX",
        mobile:9135467642,
        email:"diya@gmail.com",
        course:"BCA",
        session:"2023-27",
        status:0
    },
    {
        id:9,
        name:"Diya",
        fname:"XX",
        mname:"XX",
        mobile:9135467642,
        email:"diya@gmail.com",
        course:"BCA",
        session:"2023-27",
        status:0
    },
    {
        id:10,
        name:"Diya",
        fname:"XX",
        mname:"XX",
        mobile:9135467642,
        email:"diya@gmail.com",
        course:"BCA",
        session:"2023-27",
        status:1
    },
];

export default StudentArray;